(function(){"use strict";
const invitation=BuergeramtLink.fromHash(),number=document.getElementById("phone-number"),status=document.getElementById("phone-status"),read=document.getElementById("phone-read"),call=document.getElementById("phone-call"),line=document.getElementById("phone-call-line"),answer=document.getElementById("phone-answer"),decline=document.getElementById("phone-decline");
const platform=navigator.userAgentData?.platform||navigator.userAgent||"";document.documentElement.dataset.phoneOs=/Android/i.test(platform)?"android":/iPhone|iPad|iOS/i.test(platform)?"ios":"generic";
const clock=document.getElementById("phone-time");function updateClock(){clock.textContent=new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit"}).format(new Date())}updateClock();setInterval(updateClock,30000);
if(!invitation){status.textContent="Dieses Ticket hat keine gültige Warteschlange.";return}
const link=new BuergeramtLink("phone",invitation);let currentCall="",resolved=false,policeIndex=-1,audioContext=null,staticSource=null,voiceGeneration=0;
let wakeLock=null;async function keepAwake(){try{wakeLock=await navigator.wakeLock?.request("screen")||null}catch{wakeLock=null}}
function stopStatic(){try{staticSource?.stop()}catch{}staticSource=null}
function startStatic(){if(!audioContext)return;stopStatic();const buffer=audioContext.createBuffer(1,Math.floor(audioContext.sampleRate*.32),audioContext.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(Math.random()*2-1)*(.45+.55*Math.random());const source=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain();source.buffer=buffer;source.loop=true;filter.type="bandpass";filter.frequency.value=2200;filter.Q.value=.45;gain.gain.value=.035;source.connect(filter).connect(gain).connect(audioContext.destination);source.start();staticSource=source}
function showPolice(text){const generation=++voiceGeneration;stopStatic();speechSynthesis.cancel();line.textContent=text;line.hidden=false;const utterance=new SpeechSynthesisUtterance(text);utterance.lang="de-DE";utterance.rate=.87;utterance.pitch=.66;utterance.volume=.9;utterance.voice=speechSynthesis.getVoices().find(v=>/^de/i.test(v.lang)&&/male|daniel|stefan|markus|martin|thomas|tim/i.test(v.name))||speechSynthesis.getVoices().find(v=>/^de/i.test(v.lang))||null;utterance.onend=utterance.onerror=()=>{if(generation===voiceGeneration)stopStatic()};requestAnimationFrame(()=>{if(!call.hidden&&line.textContent===text){startStatic();speechSynthesis.speak(utterance)}})}
function endCall(kind){if(resolved||!currentCall)return;resolved=true;link.send(kind,{id:currentCall});if(kind==="decline"){call.hidden=true;status.textContent="Anruf abgelehnt. Der Termin läuft weiter."}else{answer.hidden=true;decline.hidden=true;line.hidden=false;try{audioContext=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume()}catch{}showPolice(line.textContent);status.textContent="Anruf angenommen."}}
link.addEventListener("status",e=>{status.textContent=e.detail});
link.addEventListener("connected",()=>{link.send("hello");status.textContent="Verbunden. Die Nummer wird vom Amt bestätigt."});
link.addEventListener("message",e=>{const m=e.detail;if(m.type==="ticket"&&/^[A-Z]-\d{3}$/.test(m.number||"")){number.textContent=m.number;read.disabled=false;status.textContent="Ihre Nummer ist eingegangen. Bestätigen Sie den Erhalt."}if(m.type==="call"&&m.id==="grass"&&typeof m.line==="string"&&m.line.length<350){currentCall=m.id;resolved=false;policeIndex=-1;line.textContent=m.line;line.hidden=true;answer.hidden=false;decline.hidden=false;call.hidden=false;if(navigator.vibrate)navigator.vibrate([240,150,240,150,240])}if(m.type==="police-line"&&resolved&&m.id===undefined&&Number.isInteger(m.index)&&m.index>policeIndex&&m.index<3&&typeof m.line==="string"&&m.line.length<350){policeIndex=m.index;showPolice(m.line)}if(m.type==="done"){voiceGeneration++;stopStatic();speechSynthesis.cancel();call.hidden=true;status.textContent="Dieser Termin wurde am Schalter bearbeitet."}});
read.onclick=()=>{if(link.send("ticket-read")){read.disabled=true;status.textContent="Wartenummer bestätigt. Bitte bleiben Sie erreichbar.";document.documentElement.requestFullscreen?.({navigationUI:"hide"}).catch(()=>{});keepAwake()}};
answer.onclick=()=>endCall("answer");decline.onclick=()=>endCall("decline");
link.start().catch(e=>{status.textContent="Verbindung fehlgeschlagen: "+e.message});
document.addEventListener("visibilitychange",()=>{if(!document.hidden&&!read.disabled)keepAwake()});
window.addEventListener("pagehide",()=>{voiceGeneration++;stopStatic();speechSynthesis.cancel();audioContext?.close();wakeLock?.release();link.close()});
})();
