(() => {
  "use strict";
  const catalog=window.GermanySimulatorAudioText;
  const quizPeople=window.GermanySimulatorQuizCharacters.characters;
  const spriteRoot="./assets/sprite-archive/pre-rig-20260921/assets/";
  const atlases={
    merz:{file:"border-pourer-sprite.png",cols:32,rows:6,cycle:41.6,directions:{right:1,left:3,down:0,up:4},action:2},
    merkel:{file:"merkel-sprite.png",cols:24,rows:5,cycle:41.6,directions:{right:2,left:1,down:4,up:3}},
    bayern:{file:"bayern-walker-sprite.png",cols:32,rows:4,cycle:41.6,directions:{right:1,left:3,down:0,up:2}},
    alice:{file:"alice-weidel-sprite.png",cols:32,rows:2,cycle:41.6,directions:{right:0,left:1,down:0,up:1}},
    "towel-man":{file:"crowd-towel-man.png",cols:32,rows:3,cycle:24,directions:{right:0,left:0,down:1,up:2},mirrorLeft:true},
    "towel-woman":{file:"crowd-towel-woman.png",cols:32,rows:3,cycle:24,directions:{right:0,left:0,down:1,up:2},mirrorLeft:true}
  };
  const images=new Map();
  function imageFor(kind){const a=atlases[kind];if(!a)return null;if(!images.has(kind)){const img=new Image();img.src=spriteRoot+a.file;images.set(kind,img)}return images.get(kind)}
  const line=(trigger,text,clip="")=>({trigger,text,clip});
  const clipTrigger=trigger=>trigger?.startsWith("character.")?"Nearby or E":trigger==="player.law-power"?"§ / Q · law power":trigger?.startsWith("player.germanness.")?"Germanness "+trigger.split(".").at(-1):trigger?.startsWith("rule.")?"Rule display or rotation":trigger?.startsWith("train.")?"Rail proximity or obstruction":trigger?.startsWith("quiz.")?"Wrong quiz answer":trigger?.startsWith("pedestrian.")?"Nearby · sidewalk":trigger||"Recorded line";
  const clipsFor=(voiceId,predicate=()=>true)=>Object.values(catalog.clips).filter(item=>item.voiceId===voiceId&&predicate(item)).map(item=>line(voiceId==="station"?(item.id.includes("buxtehude")?"Track or player obstruction":"Station platform nearby"):clipTrigger(item.trigger),item.text,item.path));
  const npcGerman=["Also das ist jetzt aber auch nicht so gedacht.","Kann man machen. Muss man aber wirklich nicht.","Ich möchte mich nicht beschweren, aber ich beschwere mich.","Dafür gibt es bestimmt ein Formular.","Früher war hier weniger Vorgang.","Sie stehen minimal im Weg.","Das ist bestimmt wegen der Baustelle. Die ist seit 2009 da.","Dafür bin ich nicht zuständig.","Ordnung muss schon sein.","Haben Sie dafür einen Termin?"];
  const npcBerlin=["Also this ist jetzt aber auch nicht so gedacht.","Kann man machen. Muss man aber really nicht.","Ich möchte mich nicht complainen, aber ich complain jetzt.","Dafür gibt es bestimmt ein Formular, probably online but not really.","Früher war hier weniger process.","Sie stehen minimal im way.","Das ist bestimmt wegen der Baustelle. Die ist since 2009 da.","Dafür bin ich not responsible.","Ordnung muss schon sein, you know.","Haben Sie dafür einen appointment?"];
  const pedestrian={
    berlin:{
      sidewalk:["HALT! You are standing im normierten Gehwegprofil!","Stop! Sie blockieren den Durchgang according to my interpretation!","Sie sind im way. I was hier first, administratively speaking!","Hast du schon Kehrwoche gemacht? Then respect die Gehordnung!","Das Leben ist kein Ponyhof. Move aus meiner Lauflinie!","Hast du tomatoes on den Augen? This is clearly mein Gehweg!"],
      grass:["HALT! Off the grass! Runter vom Rasen, immediately!","STOP! Der Rasen is for looking, not for walking!","Haben Sie eine Halmbetretungserlaubnis? Of course not!","Jetzt haben wir den Salat, and Sie stehen mitten im Grünbereich!"],
      road:["HALT! Off the street! Runter von der Fahrbahn!","STOP! The Zebrastreifen is literally right there!","Verkehrsrowdy! Your Querungswinkel is completely unapproved!","Hast du tomatoes on den Augen? Weg von der Straße!"]
    },
    germany:{
      sidewalk:["HALT! Sie stehen im normierten Gehwegprofil!","STOPP! Sie blockieren den Durchgang nach meiner Auslegung!","Sie sind im Weg. Ich war verwaltungsrechtlich zuerst hier!","Hast du schon Kehrwoche gemacht? Dann kennen Sie doch die Gehwegordnung!","Das Leben ist kein Ponyhof. Verlassen Sie meine Lauflinie!","Haben Sie Tomaten auf den Augen? Das ist eindeutig mein Gehweg!"],
      grass:["HALT! Runter vom Rasen!","STOPP! Der Rasen ist anzusehen, nicht zu betreten!","Haben Sie eine Halmbetretungserlaubnis? Natürlich nicht!","Jetzt haben wir den Salat, und Sie stehen mitten in der Grünfläche!"],
      road:["HALT! Runter von der Fahrbahn!","STOPP! Der Zebrastreifen ist gleich dort!","Verkehrsrowdy! Ihr Querungswinkel ist vollständig ungenehmigt!","Haben Sie Tomaten auf den Augen? Weg von der Straße!"]
    }
  };
  const towel={
    "towel-man":{berlin:["Dieser Platz ist seit 07:04 durch textile Willenserklärung reserved.","Please Abstand halten: Das Handtuch befindet sich im Vorverfahren."],germany:["Dieser Platz ist seit 07:04 Uhr durch textile Willenserklärung reserviert.","Bitte Abstand halten: Das Handtuch befindet sich im Vorverfahren."]},
    "towel-woman":{berlin:["Die Liege ist not frei; die Reservierung trocknet nur kurz.","Your Schatten fällt in meinen amtlich vorgemerkten Sonnenkorridor."],germany:["Die Liege ist nicht frei; die Reservierung trocknet nur kurz.","Ihr Schatten fällt in meinen amtlich vorgemerkten Sonnenkorridor."]}
  };
  const policeLines={berlin:["HALT! Stop mal immediately!","Nicht auf ze grass, bitte!","Ausweis, ID, irgendwas Officiales!","Please leave den Grünbereich sofort!","Das ist so wirklich not vorgesehen!","Bleiben Sie hinter ze line!"],germany:["HALT! STEHENBLEIBEN!","NICHT ÜBER DEN RASEN!","AUSWEIS BITTE!","SIE VERLASSEN SOFORT DEN GRÜNBEREICH!","DAS IST SO NICHT VORGESEHEN!","BLEIBEN SIE HINTER DER LINIE!"]};
  const playerLines={
    berlin:{train:"Natürlich verpasse ich den Zug. Even mein Scheitern hat Verspätung.",wrongOffice:"Great. Falsches Amt. Ich kriege nicht einmal meine eigene Zuständigkeit hin.",bicycle:"Natürlich stehe ich im Radweg. I can't even fail in der richtigen Spur.",fax:"Ich werde nie anything amounten, außer vielleicht zu einem sauber abgehefteten Irrtum.",coffee:"Nicht einmal der Kaffeeautomat wants responsibility für mich.",pfand:"Nicht einmal Leergut. I bring literally nichts Verwertbares mit.",wrongTask:"Natürlich ist das noch nicht mein Vorgang. Nichts ist je mein Vorgang, außer das Scheitern.",lost:"Hier ist niemand zuständig. Wahrscheinlich bin ich selbst für nichts zuständig.",exhaustion:"Natürlich bin ich erschöpft. Andere schaffen Dinge; ich verwalte nur mein Scheitern.",deadline:"Schon wieder ein Tag weg. I am late sogar für mein eigenes Scheitern."},
    germany:{train:"Natürlich verpasse ich den Zug. Sogar mein Scheitern hat Verspätung.",wrongOffice:"Großartig. Falsches Amt. Ich bekomme nicht einmal meine eigene Zuständigkeit hin.",bicycle:"Natürlich stehe ich im Radweg. Ich kann nicht einmal in der richtigen Spur scheitern.",fax:"Ich werde nie etwas zustande bringen, außer vielleicht einen sauber abgehefteten Irrtum.",coffee:"Nicht einmal der Kaffeeautomat will für mich zuständig sein.",pfand:"Nicht einmal Leergut. Ich bringe wirklich nichts Verwertbares mit.",wrongTask:"Natürlich ist das noch nicht mein Vorgang. Nichts ist je mein Vorgang, außer das Scheitern.",lost:"Hier ist niemand zuständig. Wahrscheinlich bin ich selbst für nichts zuständig.",exhaustion:"Natürlich bin ich erschöpft. Andere schaffen Dinge; ich verwalte nur mein Scheitern.",deadline:"Schon wieder ein Tag verloren. Ich komme sogar für mein eigenes Scheitern zu spät."}
  };
  const merzLines=["Das Rote Rathaus zu stürmen? Das muss ein Ende haben.","Mein Großvater war kein Nationalsozialist, sondern eine beeindruckende Persönlichkeit und ein erfolgreicher Bürgermeister."];
  const merkelLines=["Sie stehen hinter mir.","Wir brauchen kein Abschaltgesetz, sondern einen Ausstieg mit Augenmaß.","Ich habe eine neue Bewertung vorgenommen.","Die Risiken der Kernenergie sind nicht beherrschbar.","Wer das erkennt, muss eine neue Bewertung vornehmen.","Wir müssen uns darauf einstellen, dass wir schneller aussteigen.","Wir wollen das schaffen."];
  const quizRemark={berlin:"Ihr Deutsch klingt already quite convincing. Let us verify that completely beiläufig.",germany:"Ihr Deutsch klingt bereits recht überzeugend. Prüfen wir das ganz beiläufig."};
  const profiles=[
    {id:"player",name:"You · player character",group:"Main cast",kind:"Playable person",body:"player",speed:146,movement:"WASD or arrows at 146 world units/s; Shift runs at 1.58×. Code-native 3D limbs swing from distance travelled and settle when stopped.",trigger:"Movement, wrong office, train, fax, bicycle, Pfand, exhaustion, deadline, Germanness and § law power",voice:"Browser speech for inner monologue; recorded Thorsten clips for Germanness and § power",region:"berlin",lines:r=>[...Object.entries(playerLines[r]).map(([context,text])=>line("Inner monologue · "+context,text)),...clipsFor("thorsten",item=>item.trigger?.startsWith("player."))]},
    {id:"merz",name:"Friedrich Merz",group:"Main cast",kind:"Brandmauer figure",body:"merz",speed:68,movement:"Moves along the Brandmauer at up to 68 units/s, crosses lanes and pours. The 32-frame atlas follows travelled distance; the pouring action has its own rows.",trigger:"Nearby in either region while wanted level is below two; E opens direct dialogue",voice:"German browser speech; independent saved voice profile is not shipped",region:"berlin",lines:()=>merzLines.map(text=>line("Proximity or E dialogue",text))},
    {id:"merkel",name:"Angela Merkel",group:"Main cast",kind:"Energy district",body:"merkel",speed:38,movement:"Walks an eight-point loop at 38 units/s, reverses when blocked. Side, front and back atlas views advance from actual distance.",trigger:"Nearby or E; standing behind her selects the directional line",voice:"Two shipped excerpts plus German browser speech",region:"germany",lines:()=>[...clipsFor("merkel"),...merkelLines.map((text,i)=>line(i===0?"Behind her · proximity or E":"Proximity or E",text))]},
    {id:"bayern",name:"Markus Söder · Bayern-Beauftragter",group:"Main cast",kind:"Roaming Bayern official",body:"bayern",speed:52,movement:"Chooses connected sidewalk waypoints at 52 units/s, waits 2–6 seconds at stops and changes branch when blocked. The 32-frame atlas follows distance.",trigger:"Nearby or E, on the Deutschland side",voice:"Eight shipped recordings",region:"germany",lines:()=>clipsFor("bayern")},
    {id:"alice",name:"Alice Weidel",group:"Main cast",kind:"Roaming political character",body:"alice",speed:78,movement:"Walks a short vertical route at 78 units/s and reverses at each end or obstacle. The two-row, 32-frame atlas follows distance.",trigger:"Nearby or E, on the Deutschland side",voice:"Five shipped recordings",region:"germany",lines:()=>clipsFor("alice")},
    {id:"police",name:"Police officer",group:"Main cast",kind:"Wanted response",body:"police",speed:92,movement:"Code-native 3D officer pursues the player, steers around solids, and escorts on contact. Gait follows movement and settles at rest.",trigger:"Wanted escalation and nearby enforcement; regional bark pool",voice:"Browser speech; separate saved officer voice profile is not shipped",region:"berlin",lines:r=>policeLines[r].map(text=>line("Wanted response · bark",text))}
  ];
  const namedNpcs=["HERR KLEIN","FRAU MÜLLER","HERR SCHULZ","FRAU NEUMANN","HERR DIN","FRAU AKTENSTAPEL","HERR TÜV","FRAU SPARKASSE","HERR POST","HERR RASENAUFSICHT","FRAU ORDNUNG","HERR ARCHIV","FRAU TERMIN","HERR MIETNACHWEIS","FRAU ZEBRA","HERR FUNDSACHE","FRAU RUHE","HERR FAXROLLE","FRAU TRENNUNG"];
  for(const name of namedNpcs)profiles.push({id:"npc-"+name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-"),name,group:"Named passersby",kind:"Ordinary pedestrian",body:"npc",speed:13,movement:"Paces a short horizontal or vertical route at roughly 10–16 units/s; turns at the route ends. This is the code-native 3D pedestrian body.",trigger:"E gives two lines; proximity changes complaint by sidewalk, grass or road",voice:"Browser speech; shared pedestrian voice pool",region:"berlin",lines:r=>[...((r==="berlin"?npcBerlin:npcGerman).map(text=>line("E · direct dialogue pool",text))),...Object.entries(pedestrian[r]).flatMap(([surface,values])=>values.map(text=>line("Nearby · "+surface,text))),...(r==="germany"?clipsFor("thorsten",item=>item.trigger?.includes("pedestrian")):[])]});
  const crowdNames=["ALEX YILMAZ","SASCHA OKAFOR","TONI NGUYEN","KIM SCHMIDT","MICHA HADDAD","NIKI PETROVIĆ","CHARLIE WEBER","LOU KAYA","ROBIN DEMIR","DANI KOWALSKI","JULE ABDI","ANDREA ROSSI"];
  for(let j=0;j<crowdNames.length;j++){const name=crowdNames[(j*5+3)%crowdNames.length],archetype=j%2?"towel-woman":"towel-man";profiles.push({id:"crowd-"+name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-"),name,group:"Crowd",kind:archetype==="towel-man"?"Liegenreservierer":"Handtuchhoheit",body:archetype,speed:13+j%5,movement:"Walks a sidewalk route at 13–17 units/s. The 32-frame side/front/back atlas advances only while travelling; left travel mirrors the right-facing row.",trigger:"E gives two ordinary lines; nearby surface complaints and towel-specific sidewalk barks. Some crowd actors also approach for a quiz.",voice:"Browser speech; shared passerby profile",region:"berlin",lines:r=>[...(r==="berlin"?npcBerlin:npcGerman).map(text=>line("E · direct dialogue pool",text)),...Object.entries(pedestrian[r]).flatMap(([surface,values])=>values.map(text=>line("Nearby · "+surface,text))),...towel[archetype][r].map(text=>line("Nearby · towel archetype",text))]})}
  for(const person of quizPeople)profiles.push({id:"quiz-"+person.id,name:person.name,group:"Quiz identities",kind:person.title,body:"quiz",portrait:person.portrait,speed:15,movement:"The dossier portrait appears in the quiz modal. In the world, a selected crowd pedestrian approaches and follows for at most eight seconds; that pedestrian's towel body keeps its normal walk atlas.",trigger:"Selected for eligible "+person.categories.join(", ")+" question categories; approach, question and wrong-answer sting",voice:"Browser speech for the question; shared recorded wrong-answer sting",region:"berlin",lines:r=>[line("Approach · regional remark",quizRemark[r]),line("Question · civic example",r==="berlin"?"Wie viele Bundesländer hat die Bundesrepublik Deutschland?":"Wie viele Bundesländer hat die Bundesrepublik Deutschland?"),...clipsFor("quiz-sting")]});
  const counters=["BÜRGERAMT","HAUSVERWALTUNG","FINANZAMT","KRANKENKASSE","AMT FÜR STADTBILD","AUSLÄNDERBEHÖRDE","WURST-INSEL"];
  counters.forEach((name,index)=>profiles.push({id:"counter-"+index,name,group:"Counter voices",kind:"Building interaction · no walking actor",body:"counter",speed:0,movement:"The player interacts with the building entrance. The dialogue is attached to the office, with no visible clerk model or movement actor.",trigger:"E at the entrance; mission-dependent form dialogue or wrong-office response",voice:"German browser speech",region:"berlin",lines:r=>index===6?[line("E · food counter","Bratwurst +35 Energie. Currywurst +50 Verwaltungsmut."),line("E · food counter","Senf ist kein gültiges Aktenzeichen.")]:[line("E · correct office",r==="berlin"?"Guten Tag, hello. Bitte waiten Sie, bis Ihr Warten systemseitig confirmed wurde.":"Guten Tag. Bitte warten Sie, bis Ihr Warten verwaltungsintern erfasst wurde."),line("E · correct office",r==="berlin"?"Bitte every field ausfüllen. Auch die Felder, die später erst relevant werden.":"Füllen Sie jedes Feld aus. Auch die Felder, deren Zweck sich erst nach der Abgabe ergibt."),line("E · wrong office",r==="berlin"?"Sie sind hier basically richtig, aber für einen anderen process.":"Sie sind hier grundsätzlich richtig, aber für einen anderen Vorgang.")] }));
  profiles.push({id:"station-announcer",name:"AMT-BAHN announcer",group:"Counter voices",kind:"Train voice · no walking actor",body:"counter",speed:0,movement:"The speaker is bound to a train announcement, not a visible person. Trains move on their perimeter tracks independently.",trigger:"Four recordings near station platforms; Buxtehude on the track or when the player obstructs a train",voice:"Five shipped station-hall recordings",region:"germany",lines:()=>clipsFor("station")});
  profiles.push({id:"rule-announcer",name:"Rule announcer",group:"Counter voices",kind:"Ambient narrator · no walking actor",body:"counter",speed:0,movement:"No visible actor. The rule card rotates every 14 seconds during active play.",trigger:"First rule display and each 14-second rotation",voice:"Eleven shipped Thorsten readings",region:"germany",lines:()=>clipsFor("thorsten",item=>item.trigger==="rule.first-display-or-rotation")});
  const byId=new Map(profiles.map(person=>[person.id,person]));
  window.GermanySimulatorCharacterReview=Object.freeze({profiles,atlases});
  if(typeof document==="undefined")return;
  const $=id=>document.getElementById(id),directory=$("directory"),filter=$("filter"),region=$("region"),facing=$("facing"),action=$("action"),stage=$("stage"),ctx=stage.getContext("2d"),audio=$("clip-player");
  let current=profiles[0],playing=!matchMedia("(prefers-reduced-motion: reduce)").matches,elapsed=0,lastFrame=performance.now(),activeButton=null;
  function stopAudio(){audio.pause();audio.removeAttribute("src");audio.load();if("speechSynthesis" in window)speechSynthesis.cancel();if(activeButton){activeButton.closest("li").dataset.active="false";activeButton=null}}
  function hash(value){let h=0;for(const c of value)h=(h*31+c.charCodeAt(0))>>>0;return h}
  function speak(text,speaker){if(!("speechSynthesis" in window)){status("Browser speech unavailable here.");return}const utterance=new SpeechSynthesisUtterance(text),voices=speechSynthesis.getVoices().filter(v=>/^de(-|_)/i.test(v.lang)||/german|deutsch/i.test(v.name)),h=hash(speaker);utterance.voice=voices[h%Math.max(1,voices.length)]||null;utterance.lang="de-DE";utterance.rate=.88+(h%4)*.025;utterance.pitch=/merz|police|herr/i.test(speaker)?.68:.86+(h%5)*.035;speechSynthesis.speak(utterance)}
  function status(message){$("status").textContent=message}
  function makeRows(){stopAudio();$("audio-now").textContent="";const list=$("audio-list");list.replaceChildren();for(const item of current.lines(region.value)){const li=document.createElement("li");li.className="audio-row";const head=document.createElement("header"),details=document.createElement("div"),trigger=document.createElement("strong"),type=document.createElement("span"),button=document.createElement("button"),p=document.createElement("p");trigger.textContent=item.trigger;type.textContent=item.clip?"Shipped recording":"Browser generated voice";button.type="button";button.textContent="Play";button.setAttribute("aria-label","Play "+item.trigger+": "+item.text);p.textContent=item.text;details.append(trigger,type);head.append(details,button);li.append(head,p);list.append(li);button.addEventListener("click",async()=>{stopAudio();activeButton=button;li.dataset.active="true";$("audio-now").textContent=item.text;if(item.clip){audio.src=item.clip;try{await audio.play()}catch{type.textContent="Recording unavailable · browser voice fallback";speak(item.text,current.name)}}else speak(item.text,current.name)})}status(`${list.children.length} spoken triggers shown for ${current.name}.`)}
  function buildDirectory(){const query=filter.value.trim().toLocaleLowerCase();directory.replaceChildren();let group="",heading=null;for(const person of profiles){if(query&&!`${person.name} ${person.kind} ${person.group}`.toLocaleLowerCase().includes(query))continue;if(person.group!==group){group=person.group;heading=document.createElement("h2");heading.textContent=group;directory.append(heading)}const a=document.createElement("a");a.href="?person="+encodeURIComponent(person.id);a.textContent=person.name;if(person===current)a.setAttribute("aria-current","page");directory.append(a)}if(!directory.querySelector("a"))directory.textContent="No matching person."}
  function select(id,push=false){const person=byId.get(id)||profiles[0];current=person;if(push)history.pushState(null,"","?person="+encodeURIComponent(person.id));stopAudio();$("profile-title").textContent=person.name;$("profile-kind").textContent=person.kind;$("movement-note").textContent=person.movement;const portrait=$("quiz-portrait");portrait.hidden=!person.portrait;if(person.portrait){portrait.src=person.portrait;portrait.alt=person.name+" dossier portrait"}$("facts").replaceChildren();for(const [label,value] of [["When",person.trigger],["Audio",person.voice],["Body",person.body==="quiz"?"Crowd sprite + dossier portrait":person.body==="counter"?"No visible character":atlases[person.body]?"Shipped sprite atlas":"Code-native 3D figure"]]){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=label;dd.textContent=value;$("facts").append(dt,dd)}region.value=person.region;action.replaceChildren();for(const [value,label] of [["walk","Walk"],["idle","Idle"],...(person.body==="merz"?[["pour","Pour"]]:[])]){const option=document.createElement("option");option.value=value;option.textContent=label;action.append(option)}action.value=person.speed?"walk":"idle";facing.value=person.body==="alice"?"down":"right";elapsed=0;makeRows();buildDirectory();stage.setAttribute("aria-label",person.name+" movement preview")}
  directory.addEventListener("click",event=>{const link=event.target.closest("a[href]");if(!link)return;event.preventDefault();select(new URL(link.href).searchParams.get("person"),true);scrollTo({top:0,behavior:"instant"})});
  filter.addEventListener("input",buildDirectory);region.addEventListener("change",makeRows);addEventListener("popstate",()=>select(new URLSearchParams(location.search).get("person")));$("stop-audio").addEventListener("click",()=>{stopAudio();$("audio-now").textContent=""});$("copy-link").addEventListener("click",async()=>{const link=new URL("?person="+encodeURIComponent(current.id),location.href).href;try{await navigator.clipboard.writeText(link);$("copy-link").textContent="Copied"}catch{$("copy-link").textContent="Select URL in address bar"}setTimeout(()=>$("copy-link").textContent="Copy this link",2200)});$("pause").addEventListener("click",()=>{playing=!playing;$("pause").textContent=playing?"Pause":"Play"});$("pause").textContent=playing?"Pause":"Play";
  function drawFigure(x,y,phase,kind){ctx.save();ctx.translate(x,y);const swing=Math.sin(phase*2*Math.PI)*12,coat=kind==="police"?"#303943":kind==="player"?"#242424":"#55524d";ctx.strokeStyle=coat;ctx.lineWidth=9;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-8,-30);ctx.lineTo(-10+swing,12);ctx.moveTo(8,-30);ctx.lineTo(10-swing,12);ctx.stroke();ctx.fillStyle=coat;ctx.fillRect(-18,-78,36,51);ctx.beginPath();ctx.moveTo(-18,-65);ctx.lineTo(-26-swing*.7,-28);ctx.moveTo(18,-65);ctx.lineTo(26+swing*.7,-28);ctx.stroke();ctx.fillStyle="#cabca8";ctx.beginPath();ctx.arc(0,-93,17,0,Math.PI*2);ctx.fill();if(kind==="police"){ctx.fillStyle="#303943";ctx.fillRect(-18,-111,36,7)}ctx.restore()}
  function draw(now){const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;if(playing)elapsed+=dt;ctx.clearRect(0,0,400,290);ctx.fillStyle="#a7a39a";ctx.fillRect(0,0,400,290);ctx.strokeStyle="#dfd9cc";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(42,202);ctx.lineTo(358,202);ctx.stroke();const speed=current.speed||0,moving=action.value==="walk"&&speed>0,phase=moving?(elapsed*speed/190)%1:0,direction=facing.value,travel=moving?phase*210:105,x=direction==="left"?306-travel:direction==="right"?94+travel:200,y=direction==="up"?230-travel*.55:direction==="down"?115+travel*.55:194;ctx.strokeStyle="#756e63";ctx.setLineDash([5,6]);ctx.beginPath();if(direction==="left"||direction==="right"){ctx.moveTo(70,194);ctx.lineTo(330,194)}else{ctx.moveTo(200,100);ctx.lineTo(200,235)}ctx.stroke();ctx.setLineDash([]);const visualBody=current.body==="quiz"?"towel-man":current.body,a=atlases[visualBody],img=imageFor(visualBody),spriteFrame=action.value==="idle"?0:Math.floor((elapsed*speed/(a?.cycle||41.6)%1)*(a?.cols||1)),row=action.value==="pour"?a.action:a?.directions[direction];if(a&&img?.complete&&img.naturalWidth){const sw=img.naturalWidth/a.cols,sh=img.naturalHeight/a.rows;ctx.save();if(direction==="left"&&a.mirrorLeft){ctx.translate(x*2,0);ctx.scale(-1,1)}ctx.drawImage(img,spriteFrame*sw,row*sh,sw,sh,x-69,y-120,138,138);ctx.restore()}else if(current.body!=="counter")drawFigure(x,y,elapsed*speed/41.6,current.body==="police"?"police":current.body==="player"?"player":"npc");if(current.body==="counter"){ctx.fillStyle="#443e35";ctx.fillRect(120,126,160,64);ctx.fillStyle="#e9e3d5";ctx.font='700 22px "Preview Sans"';ctx.textAlign="center";ctx.fillText("§",200,166)}ctx.fillStyle="#2b2925";ctx.font='700 14px "Preview Sans"';ctx.textAlign="left";ctx.fillText(`${action.value.toUpperCase()} · ${speed} units/s`,12,24);requestAnimationFrame(draw)}
  select(new URLSearchParams(location.search).get("person"));requestAnimationFrame(draw);
})();
