import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import vm from "node:vm";
const source=readFileSync(new URL("../game.js",import.meta.url),"utf8");
function functionSource(name){const start=source.indexOf(`function ${name}(`),open=source.indexOf("{",start);assert.ok(start>=0);let depth=1,quote=null,escape=false;for(let i=open+1;i<source.length;i++){const ch=source[i];if(quote){if(escape)escape=false;else if(ch==="\\")escape=true;else if(ch===quote)quote=null;continue}if(ch==='"'||ch==="'"||ch==="`"){quote=ch;continue}if(ch==="{")depth++;else if(ch==="}"&&!--depth)return source.slice(start,i+1)}throw new Error(name)}
function harness(){
 const h={WORLD:{w:10960,h:5360},CITY:{w:9840,h:4240},RAIL_GUTTER:560,crossings:[],window:{Germany3D:{ready:true,isVehicleVisible:()=>false}},player:{x:2000,y:1700,r:16,vx:0,vy:0,facing:0,energy:100},goerlitzerPark:{x:10000,y:4000,w:100,h:100},kiesingerMemorial:{x:10000,y:4500},buildings:[],props:[],normObjects:[],trees:[],trains:[],policeVehicles:[],police:[],npcs:[],policeHelicopters:[],TREE_RADIUS:38,TRAIN_CAR_HALF_LENGTH:122,TRAIN_CAR_HALF_WIDTH:46,state:{wanted:2,region:"berlin"},POLICE_RESPONSE_CARS:[0,0,1,2,3,4],POLICE_RESPONSE_HELICOPTERS:[0,0,0,0,1,2],clamp:(n,a,b)=>Math.max(a,Math.min(b,n)),dist:(ax,ay,bx,by)=>Math.hypot(ax-bx,ay-by),offsetWorldPoint:p=>({...p,x:p.x+560,y:p.y+560}),spawnPointVisible:()=>false,groundResponsePoint:()=>null,onGardenGrass:()=>false,performance:{now:()=>0},playPolicePassby:()=>{},particles:[],playTrafficHorn:()=>{},shoutTrafficDriver:()=>{},enterWirtschaftswunder:()=>{},width:100,height:100,project:(x,y,z=0)=>({x:x+z*.25,y:y-z})};
 vm.createContext(h);const between=(a,b)=>source.slice(source.indexOf(a),source.indexOf(b,source.indexOf(a)+a.length));
 vm.runInContext(`${between("const horizontalRoads=","const SIDEWALK_WIDTH=")}\nconst BORDER_Y=1680;\n${between("const VEHICLE_RENDER_SCALE=","const borderGates=")}\n${between("const STATION_RISE=","const TRAIN_CAR_OFFSETS=")}\nglobalThis.actualTraffic=trafficCars;globalThis.approaches=vehicleApproaches;`,h);
 const names=["normObjectRadius","propRadius","groundContactBlocks","vehicleBodyDistance","orientedBodySeparation","vehicleMotionBlocked","vehicleOnRoad","responderBlocked","nearestDrivingRoad","policeDrivingTarget","driveGroundVehicle","policeDrivingClearance","responseSpawn","retirePoliceVehicle","finishPoliceExitRecovery","syncPoliceResponse","updatePoliceResponse","trafficForwardGap","trafficGroundGap","updateTraffic","updateWirtschaftswunderCar"];
 vm.runInContext(names.map(functionSource).join("\n"),h);const stop=source.indexOf("const stableSpriteRoot="),benchStart=source.lastIndexOf("for(const station of stations){",stop);vm.runInContext(source.slice(benchStart,stop),h);return h;
}
function verifyExitRecovery(dt,y,angle){
 const h=harness();h.actualTraffic.length=0;h.state.wanted=0;h.player.y=5000;const car={x:5050,y,angle,roadIndex:5,roadBound:true,lifecycle:"active",speed:237,driveSpeed:50,steeringAngle:0,orbit:0,avoid:1,index:0,hitCooldown:1,passbyReady:false};h.policeVehicles=[car];let reverseDistance=0,forwardDistance=0,switchedAt=null,neutral=false;
 for(let frame=0;frame<Math.ceil(180/dt)&&h.policeVehicles.includes(car);frame++){
  const before={x:car.x,y:car.y,angle:car.angle,recovering:car.exitBackwards,road:car.exitTarget?.road};h.updatePoliceResponse(dt);const distance=h.dist(before.x,before.y,car.x,car.y);assert.ok(distance<=237*dt+1e-6,"recovery changes gear without a position jump");assert.ok(Math.abs(car.angle-before.angle)<=2*Math.asin(Math.min(1,distance/210*Math.tan(.62)))+1e-6,"recovery preserves displacement-based yaw without a stationary spin");assert.ok(h.vehicleOnRoad(car.x,car.y,car.angle),"the whole car stays inside the physical road union throughout recovery");
  if(car.driveSpeed<0)reverseDistance+=distance;
  if(before.recovering&&!car.exitBackwards){switchedAt=frame*dt;const c=Math.cos(before.angle),s=Math.sin(before.angle),ex=Math.abs(c)*94+Math.abs(s)*51,ey=Math.abs(s)*94+Math.abs(c)*51;assert.ok(Math.abs(s)<=.25&&before.x-ex>=before.road.x&&before.x+ex<=before.road.x+before.road.w&&before.y-ey>=before.road.y&&before.y+ey<=before.road.y+before.road.h,"forward departure begins only after the complete nearly-horizontal body clears the junction");assert.equal(Math.sign(car.exitTarget.x-car.x),Math.sign(c),"forward exit follows the current nose direction")}
  if(switchedAt!==null){if(car.driveSpeed===0)neutral=true;if(car.driveSpeed>0){assert.ok(neutral,"reverse motion must brake to zero before forward acceleration");forwardDistance+=distance}}
 }
 assert.ok(switchedAt!==null&&switchedAt<40,"dead-end reverse is limited to the first reachable junction");assert.ok(reverseDistance<1400,"the car cannot reverse along the entire city to retire");assert.ok(forwardDistance>3000,"the recovered car drives forward along its departure road");assert.equal(h.policeVehicles.includes(car),false);assert.ok(h.vehicleFullyOffMap(car.x,car.y,car.angle));return{dt,y,switchedAt,reverseDistance,forwardDistance};
}
if(process.argv.includes("--exit-recovery")){
 for(const dt of [1/60,1/30,.1])for(const [y,angle] of [[900,-Math.PI/2],[4500,Math.PI/2]])console.log(JSON.stringify(verifyExitRecovery(dt,y,angle)));
 console.log("Dead-end reverse stays bounded to junction recovery, brakes to zero and departs forward at60/30/10Hz");process.exit(0);
}
verifyExitRecovery(.1,900,-Math.PI/2);
{
 const h=harness();assert.equal(h.actualTraffic.length,24);assert.ok(h.actualTraffic.every(car=>car.x>=710&&car.x<=10250),"initial city population remains prepopulated rather than live-spawned on camera");assert.equal(h.approaches.length,6);assert.equal(h.crossings.length,6,"every side-platform route has a marked crossing through its driving band");for(const crossing of h.crossings){const approach=h.approaches.find(r=>r.side===crossing.stationId.split('-')[0]&&r.y===crossing.y);assert.equal(crossing.h,approach.h);assert.equal(crossing.w,145);assert.equal(crossing.uncontrolled,true)}assert.match(source,/const onRoad=\(x,y\)=>\[\.\.\.roads,\.\.\.vehicleApproaches\]/,"road laws classify the actual through-station vehicle surface");
 for(const x of [205,257.5,310,455,507.5,560]){const expected=x===205||x===560?0:x===257.5||x===507.5?.15:.3;assert.ok(Math.abs(h.vehicleElevation(x,1575)-expected)<1e-9,"station road approaches rise and fall continuously without a curb teleport");assert.ok(Math.abs(h.stationElevation(x,1575)-expected)<1e-9,"walking feet use the same side access surface as vehicle wheels")}
 assert.equal(h.props.filter(p=>p.fallbackOnly).length,12,"side-station furniture has one canonical semantic record per visible bench");for(const bench of h.props){assert.equal(h.propRadius(bench),35);const car={x:bench.x,y:bench.y,angle:0};assert.equal(h.vehicleMotionBlocked(car.x,car.y,car,car.x,car.y),true,"a native station bench is a solid object")}
 h.window.Germany3D.ready=false;assert.equal(h.vehicleFullyOffMap(-100,50,0),true);assert.equal(h.vehicleCameraVisible(-100,50,0),true,"an off-map body can still project into the native camera and must remain visible");assert.equal(h.vehicleCameraVisible(-2200,50,0),false);assert.equal(h.vehicleCameraVisible(50,50,0),true,"projected body bounds detect a car enclosing the view even when no vertex is inside it");
}
for(const dir of [1,-1]){
 const h=harness();h.actualTraffic.length=0;h.player.x=dir>0?1000:10000;const car=h.responseSpawn("car",0);assert.ok(car);assert.equal(car.entryDir,dir);assert.ok(h.vehicleFullyOffMap(car.x,car.y,car.angle));assert.equal(h.vehicleCameraVisible(car.x,car.y,car.angle),false);h.policeVehicles.push(car);
 const stageX=car.x;h.window.Germany3D.isVehicleVisible=()=>true;assert.equal(h.responseSpawn("car",1),null,"live staging waits if its complete body is in the actual camera");h.window.Germany3D.isVehicleVisible=()=>false;
 // A coach occupies the approach: entry respects its full solid body before proceeding.
 const railX=dir>0?232:10728,coach={x:railX,y:car.y,angle:Math.PI/2};h.trains=[{cars:[coach]}];
 for(let frame=0;frame<1000;frame++){h.updatePoliceResponse(.025);assert.ok(h.vehicleOnRoad(car.x,car.y,car.angle));assert.ok(h.orientedBodySeparation({...car,halfLength:94,halfWidth:51},{...coach,halfLength:122,halfWidth:46})>=-1e-6,"entry cannot bypass a rail coach")}
 assert.ok(dir>0?car.x>stageX:car.x<stageX,"a staged car physically drives toward the map");assert.equal(car.lifecycle,"entering");h.trains=[];
 for(let frame=0;frame<1000&&car.lifecycle==="entering";frame++){const x=car.x,y=car.y;h.updatePoliceResponse(.025);assert.ok(h.dist(x,y,car.x,car.y)<=300*.025+1e-6,"entry is bounded driving motion, never an on-map teleport")}
 assert.equal(car.lifecycle,"active");assert.ok(!h.vehicleFullyOffMap(car.x,car.y,car.angle));h.state.wanted=0;h.updatePoliceResponse(.025);assert.equal(car.retiring,true);assert.ok(h.policeVehicles.includes(car),"dismissal keeps the on-map car alive for its road departure");
 h.window.Germany3D.isVehicleVisible=()=>true;
 for(let frame=0;frame<4000&&!h.vehicleFullyOffMap(car.x,car.y,car.angle);frame++){h.updatePoliceResponse(.025);assert.ok(h.policeVehicles.includes(car));assert.ok(h.vehicleOnRoad(car.x,car.y,car.angle))}
 assert.ok(h.vehicleFullyOffMap(car.x,car.y,car.angle),"retirement reaches a real map exit");h.updatePoliceResponse(.025);assert.ok(h.policeVehicles.includes(car),"whole off-map cars remain alive while still visible");h.window.Germany3D.isVehicleVisible=()=>false;h.updatePoliceResponse(.025);assert.equal(h.policeVehicles.includes(car),false,"removal requires the whole body off-map and off-camera");
}
// Retirement chooses a reachable crossing ahead on actual narrow vertical roads.
for(const [angle,y] of [[Math.PI/2,2100],[-Math.PI/2,2100],[-Math.PI/2,900]]){
 const h=harness();h.actualTraffic.length=0;h.state.wanted=0;h.player.y=5000;const car={x:5050,y,angle,roadIndex:5,roadBound:true,lifecycle:"active",speed:237,driveSpeed:50,steeringAngle:0,orbit:0,avoid:1,index:0,hitCooldown:1,passbyReady:false};h.policeVehicles=[car];
 for(let frame=0;frame<20000&&h.policeVehicles.includes(car);frame++){h.updatePoliceResponse(.025);if(h.policeVehicles.includes(car))assert.ok(h.vehicleOnRoad(car.x,car.y,car.angle),"vertical-road retirement keeps the whole car on its physical route")}
 assert.equal(h.policeVehicles.includes(car),false,"a dismissed car reaches an off-map exit from a narrow road, including a dead-end backing departure");assert.ok(h.vehicleFullyOffMap(car.x,car.y,car.angle));
}
for(const dir of [1,-1]){
 const h=harness();h.actualTraffic.length=0;h.player.y=5000;const entry=dir>0?-2200:13160,end=dir>0?13160:-2200,car={x:end-dir*.1,y:1445,laneY:1445,dir,angle:dir>0?0:Math.PI,lane:"test",roadIndex:0,vortexPhase:"road",speed:120,cruiseSpeed:120,acceleration:60,honkCooldown:0,honkFlash:0,hold:0};h.actualTraffic.push(car);
 h.window.Germany3D.isVehicleVisible=()=>true;h.updateTraffic(.025);assert.equal(car.x,end,"traffic waits at its off-map endpoint while either lifecycle endpoint is visible");h.window.Germany3D.isVehicleVisible=()=>false;car.speed=120;h.updateTraffic(.025);assert.ok(Math.abs(car.x-entry)<4);assert.ok(h.vehicleFullyOffMap(car.x,car.y,car.angle),"cyclic transfer connects two wholly off-map endpoints");
 car.vortexPhase="swallowed";car.x=1380;car.y=2060;car.vortexRespawn=0;h.updateWirtschaftswunderCar(car,.025);assert.equal(car.vortexPhase,"road");assert.equal(car.x,entry);assert.ok(h.vehicleFullyOffMap(car.x,car.y,car.angle),"authored swallowing still restores its actor at a hidden off-map entry");
}
console.log("Whole-body off-map/camera staging, continuous station/rail entry, road retirement, hidden traffic wrap and vortex restoration OK");
